// src/routes/+page.svelte
<script lang="ts">
	import { SERVER_STATUS_DEPENDS_KEY } from '$lib/pages/index/constants';
	import { invalidate } from '$app/navigation';
	import { styles } from '$lib/pages/index/styles.css';
	import { formatUsage } from '$lib/pages/index/utils';
	import type { PageProps } from './$types';
	import { onMount } from 'svelte';

	let { data }: PageProps = $props();
	let isUpdating = $state(false);

	async function refreshData() {
		isUpdating = true;
		try {
			await invalidate(SERVER_STATUS_DEPENDS_KEY);
		} finally {
			isUpdating = false;
		}
	}

	onMount(() => {
		const interval = setInterval(refreshData, 5000);
		return () => clearInterval(interval);
	});
</script>

<main class={styles.container}>
	<h1>Ikana's home server</h1>
	<p>
		This is my personal home server. If you want to know more about me, check out
		<a href="https://ikana.dev">ikana.dev</a>
	</p>

	<br />
	<br />
	<p>
		Server data: {#if isUpdating}(updating...){/if}
	</p>
	<pre>
    CPU: {data.cpu.name}
    Usage: {data.cpu.usage}%

    RAM: {formatUsage(data.ram.used)}
    Total: {formatUsage(data.ram.total)}

    Storage: {formatUsage(data.storage.used)}
    Total: {formatUsage(data.storage.total)}
    {#if data.battery.hasBattery}
			Battery: {data.battery.percentage}%
    Status: {data.battery.status}
		{/if}
  </pre>
	<h2>My apps</h2>
</main>

// src/routes/index.tsx
import { createEffect, createResource, Show, Suspense } from "solid-js";

import * as classes from "@routes/index/styles";
import { fetchServerStatus } from "@app/routesData/index/utils.server";
import CpuIcon from "@app/assets/svg/cpu.svg?solid";
import MemoryIcon from "@app/assets/svg/memory.svg?solid";
import StorageIcon from "@app/assets/svg/storage.svg?solid";
import BatteryIcon from "@app/assets/svg/battery.svg?solid";
import { formatUsage } from "@app/routesData/index/utils";

export default function Home() {
  const [serverStatus, { refetch }] = createResource(fetchServerStatus);

  const refetchInterval = setInterval(() => {
    refetch();
  }, 5000);

  createEffect(() => {
    return () => {
      clearInterval(refetchInterval);
    };
  });

  return (
    <main class={classes.container}>
      <h1>My home server :)</h1>
      <p>
        Welcome to my home server, you can't do many things here unless you're me :)
      </p>
      <Suspense>
        <Show when={serverStatus?.latest}>
          {(data) => (
            <>
              <div class={classes.grid}>
                <div class={classes.item}>
                  <CpuIcon class={classes.itemIcon} />
                  <div>
                    <p class={classes.itemData}>{data().cpu.usage}%</p>
                    <p class={classes.itemLabel}>{data().cpu.name}</p>
                  </div>
                </div>

                <div class={classes.item}>
                  <MemoryIcon class={classes.itemIcon} />
                  <div>
                    <p class={classes.itemData}>{formatUsage(data().ram.used)}</p>
                    <p class={classes.itemLabel}>of {formatUsage(data().ram.total)}</p>
                  </div>
                </div>

                <div class={classes.item}>
                  <StorageIcon class={classes.itemIcon} />
                  <div>
                    <p class={classes.itemData}>{formatUsage(data().storage.used)}</p>
                    <p class={classes.itemLabel}>of {formatUsage(data().storage.total)}</p>
                  </div>
                </div>

                <Show when={data().battery.hasBattery}>
                  <div class={classes.item}>
                    <BatteryIcon class={classes.itemIcon} />
                    <div>
                      <p class={classes.itemData}>{data().battery.percentage}%</p>
                      <p class={classes.itemLabel}>{data().battery.status}</p>
                    </div>
                  </div>
                </Show>
              </div>
            </>
          )}
        </Show>
      </Suspense>
      <br />
      <br />
      <h1>My apps</h1>
    </main>
  );
}
